name: Nucleo L476RG CAN Dev
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Install Arm GNU Toolchain
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: '12.3.Rel1' # <-- The compiler release to use

      - name: Build project
        run: |
          cd Firmware/nucleol476rg-CAN-dev
          cmake -S . -B build
          cmake --build build